// Command gen-tznames regenerates action/tznames.go, the list of IANA
// timezone names used for case-insensitive tz lookup. It reads the
// zoneinfo.zip bundled with the local Go toolchain.
//
// Usage: go generate ./action or go run ./tools/gen-tznames
package main

import (
	"archive/zip"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func goEnvGOROOT() string {
	if root := os.Getenv("GOROOT"); root != "" {
		return root
	}
	out, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func main() {
	root := goEnvGOROOT()
	if root == "" {
		fmt.Fprintln(os.Stderr, "cannot determine GOROOT")
		os.Exit(1)
	}
	zipPath := filepath.Join(root, "lib", "time", "zoneinfo.zip")

	zr, err := zip.OpenReader(zipPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "opening %s: %v\n", zipPath, err)
		os.Exit(1)
	}
	defer zr.Close()

	names := make([]string, 0, len(zr.File))
	for _, f := range zr.File {
		if f.Name == "" {
			continue
		}
		names = append(names, f.Name)
	}
	sort.Strings(names)

	var src strings.Builder
	src.WriteString(fmt.Sprintf(`// Code generated by tools/gen-tznames; DO NOT EDIT.

package action

// tzNames lists every IANA timezone name in the Go toolchain's
// zoneinfo.zip, in sorted order.
var tzNames = []string{
`))
	for _, n := range names {
		src.WriteString(fmt.Sprintf("\t%q,\n", n))
	}
	src.WriteString("}\n")

	out, err := format.Source([]byte(src.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "formatting: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join("action", "tznames.go"), out, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote action/tznames.go with %d names\n", len(names))
}
